### ISSUE TITLE
Sidebar is broken - click any link results in alert("Error Occured")

### ISSUE THREAD

**Issue by autonome** [mozilla/innovation-toolkit#3]
Go to https://toolkit.mozilla.org/methods/

And click on the sidebar links:

<img width="429" alt="screen shot 2018-08-22 at 14 48 16" src="https://user-images.githubusercontent.com/50103/44492753-7a899e80-a61a-11e8-861f-bdb72acbb4e8.png">

**Comment by autonome** [comment]
Screenshot of error:

<img width="845" alt="screen shot 2018-08-22 at 14 49 01" src="https://user-images.githubusercontent.com/50103/44492776-8b3a1480-a61a-11e8-9340-483b6a84e663.png">

**Comment by hmitsch** [comment]
Finally fixed!

In the WPengine admin interface, we set the CSP to:

**Default SRC**
```'none'
https://toolkit.mozilla.org
https://toolkit.mozilla.org/json/methods/```


<img width="554" alt="image" src="https://user-images.githubusercontent.com/869692/46229691-bd037100-c366-11e8-9a6d-07d9ddbfa73a.png">


Best regards,
   Henrik
